# DataGen Connectors
# Demo connectors for generating sample data

# Target namespace (should match where Connect is deployed)
namespace: confluent

# Connect cluster reference
connectClusterRef: connect

# Schema Registry URL
schemaRegistryUrl: http://schemaregistry.confluent.svc.cluster.local:8081

# Connectors to deploy
connectors:
  - name: datagen-users
    enabled: true
    class: io.confluent.kafka.connect.datagen.DatagenConnector
    taskMax: 1
    topic: users
    quickstart: users
    keyConverter: org.apache.kafka.connect.storage.StringConverter
    valueConverter: io.confluent.connect.avro.AvroConverter
    maxInterval: "1000"
    iterations: "10000000"

  - name: datagen-pageviews
    enabled: true
    class: io.confluent.kafka.connect.datagen.DatagenConnector
    taskMax: 1
    topic: pageviews
    quickstart: pageviews
    keyConverter: org.apache.kafka.connect.storage.StringConverter
    valueConverter: io.confluent.connect.avro.AvroConverter
    maxInterval: "500"
    iterations: "10000000"

  - name: datagen-orders
    enabled: true
    class: io.confluent.kafka.connect.datagen.DatagenConnector
    taskMax: 1
    topic: orders
    quickstart: orders
    keyConverter: org.apache.kafka.connect.storage.StringConverter
    valueConverter: io.confluent.connect.avro.AvroConverter
    maxInterval: "2000"
    iterations: "10000000"

  - name: datagen-stock-trades
    enabled: true
    class: io.confluent.kafka.connect.datagen.DatagenConnector
    taskMax: 1
    topic: stock-trades
    quickstart: stock_trades
    keyConverter: org.apache.kafka.connect.storage.StringConverter
    valueConverter: io.confluent.connect.avro.AvroConverter
    maxInterval: "100"
    iterations: "10000000"

  # Network events for ksqlDB and Flink demos
  - name: datagen-network-events
    enabled: true
    class: io.confluent.kafka.connect.datagen.DatagenConnector
    taskMax: 1
    topic: network-events
    keyConverter: org.apache.kafka.connect.storage.StringConverter
    valueConverter: org.apache.kafka.connect.json.JsonConverter
    maxInterval: "5000"  # Slow: 1 event every 5 seconds
    iterations: "10000000"
    extraConfigs:
      value.converter.schemas.enable: "false"
      schema.string: '{"type":"record","name":"NetworkEvent","namespace":"io.confluent.demo","fields":[{"name":"event_time","type":"long","arg.range":{"min":1700000000000,"max":1800000000000}},{"name":"source_ip","type":"string","arg.options":["192.168.1.10","192.168.1.20","10.0.0.5","10.0.0.15","172.16.0.100"]},{"name":"dest_ip","type":"string","arg.options":["8.8.8.8","1.1.1.1","208.67.222.222","9.9.9.9","75.75.75.75"]},{"name":"protocol","type":"string","arg.options":["TCP","UDP","HTTP","HTTPS","DNS","SSH"]},{"name":"bytes_transferred","type":"long","arg.range":{"min":100,"max":1000000}}]}'
      schema.keyfield: source_ip
