apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cfk-argocd-demo
  region: us-east-1
  version: "1.31"

vpc:
  nat:
    gateway: Disable  # Avoid NAT Gateway if blocked by SCP

managedNodeGroups:
  - name: cfk-nodes
    instanceType: m5.xlarge
    desiredCapacity: 3
    minSize: 3
    maxSize: 6
    privateNetworking: false  # Use public subnets
    volumeSize: 100
    labels:
      role: confluent
    tags:
      Environment: demo
